version: "3.7"

services:
  vue-app:
    command: > 
        sh -c "npm run serve"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vue-app
    restart: always
    ports:
      - "8080:8080"
    networks:
      - vue-network
networks:
  vue-network:
    driver: bridge